version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins-controller
    restart: unless-stopped
    ports:
      - "8081:8080"  # Utilise un autre port que ton Jenkins actuel
      - "50001:50000" # Port pour la connexion entre l'agent et Jenkins
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false

  jenkins-agent:
    build:
      context: ./agent  # Le Dockerfile se trouve dans ./agent
    container_name: jenkins-agent
    restart: unless-stopped
    user: root
    environment:
      - JENKINS_URL=http://jenkins-controller:8080
      - JENKINS_AGENT_NAME=docker-agent
      - JENKINS_SECRET=REMPLACER_PAR_VOTRE_SECRET  # Remplacer par le secret réel
      - JENKINS_WEB_SOCKET=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - jenkins

volumes:
  jenkins_home: